cp-algorithms/cp-algorithms

- src/algebra/phi-function.txt
Fixes phi-function.txt denominator error. Should be 1/p and not 1/((p)^n) .
> Fixes phi-function.txt denominator error. Should be 1/p and not 1/((p)^n) .

- src/algebra/binary-exp.md
Following #117 , use ``` instead of \tab for code format.
> Use ``` code format in binary-exp

- src/contrib.md
Without it, I get the following error:
> Adding backticks to correct formatting

- src/algebra/module-inverse.md
Hi guys! Please merge this into the site.
Changed "biggest exponent 'e' " to 'c' in line 144. That a spelling mistake.
> Changed a typo at line number 144

- src/algebra/big-integer.md
- src/index.md
In the #167 it was proposed to change "long" to "bignum". However I've checked with google keyword tools and found that "bignum" is not that often used, so straight substitution would reduce chances people find this page from search. It also seems that "arithmetic" should not have "s" at the end. Not quite sure about this, but took wikipedia as example.
> Adding word "bignum" to long arithmetic article

- src/algebra/fft.md
(w_n)^n != 1 (mod p), 1 <= k < n
to
(w_n)^k != 1 (mod p), 1 <= k < n
> Typo in an equation in FFT

- src/string/suffix-array.md
In application finding LCP of 2 substrings without additional memory, the answer's formula min{p[i], p[i+1], ..., p[j-1]} is wrong. p is array of index. The right formula should be min(lcp[i], lcp[i+1], ..., lcp[j-1]).
> Fixed typo and formula

- src/algebra/sieve-of-eratosthenes.md
Changed max(start_idx, 2) * p to max(start_idx, p) * p. This is done so that we always start from the max. of the smallest multiple of p in the range [l, r] and p * p. It is more beneficial to start from p * p rather than 2 * p as lower multiples of p would have been covered by the smaller prime factors.
> Reduced number of operations in block sieve code

- src/graph/strongly-connected-components.md
The 'used' vector in the code of SCC should be of type bool, not char
> Fixed bug in strongly connected components

- src/algebra/binary-exp.md
- src/others/josephus_problem.md
Found some issues when poking at the book again. Binary exponentiation actually had an error even in the html version, otherwise it's all language annotations for code and fixes to make things more LaTeX friendly.
Speaking of the book. Sorry for not coming back to you after discussing things in my previous PR.  I tidied my stuff up a bit and created a [repo](https://github.com/algmyr/e-maxx-eng-book) for it. There are heaps of things to be improved, but it's a somewhat user friendly proof of concept.
(I've got no idea where I would mention something like the book repo. I decided on the PR since I was writing it anyway. Making an issue here to promote my repo just felt wrong.)
> Fixes to binexp and Josephus

- src/data_structures/sqrt-tree.md
- src/string/manacher.md
Some (two) of the problem listings were sections rather than subsections. This caused some spurious sections mentioned in https://github.com/algmyr/e-maxx-eng-book/issues/2.
> Problems sections should be subsections

- src/algebra/balanced-ternary.md
- src/algebra/phi-function.md
- src/contrib.md
- src/demo-article.md
- src/dynamic_programming/divide-and-conquer-dp.md
- src/graph/strongly-connected-components.md
Fixes some headers missed by #329.
Some were part of articles that actually broke in the pdf. The others were part of `contrib.md` and `demo-article.md` that I fixed just for the sake of consistency.
> More header fixes

- src/data_structures/sqrt-tree.md
- src/graph/mpm.md
- src/sequences/k-th.md
A few articles had the wrong section depth (multiple top level sections). This places the sub(sub...)sections at the correct depth.
We now have level 4 sections (a.k.a. paragraphs in LaTeX) in `sqrt-tree.md`. That article should really be touched up to not look horrible in the pdf anyway, so I might end up doing that somewhere in the future.
> Fix section depths

- src/index.md
Implementation for #285. 
It will look like this: [link](https://jakobkogler.github.io/index.html)
e-maxx.ru only had subsections for 3 sections (Graphs, Geometry, and Algebra), but that would look just stupid. So I added subsections for all sections. Some look a little bit odd, because there is only one subsection per section. Maybe we should combine some of them (e.g. combining Miscellaneous, Schedules, Sequences and Game Theory in one big sections).
Please tell me if you are happy with it or not. And what your thoughts are.
@madhur4127 @RodionGork
> Add subsections to index

- src/string/string-hashing.md
I think it should be pretty clear that the probability of collisions is 1/modulo, not 1/base.
> Fix typo in string hashing

- src/data_structures/sparse-table.md
I added a reference to a article about a modification of the data struct called."Disjoint Sparse Table",  I could write more about the structure in the article itself, but I do not know if I can do this because the name "Disjoint Sparse Table" was created specifically by the author of the original article, and as was said in #341 I can't just make a copy of the oroginal source, but what about names ?
> Added reference about an article in sparse-table.md

- src/graph/strongly-connected-components.md
Sorting in increasing order of finish time will give the reversed topological order, saying just topological order may be misleading.
> typo in SCC documentation

- src/data_structures/segment_tree.md
In the case of adding on segments and querying for maximum, the query function did not work in logarithmic time.
> Fixed segment tree query function

- src/geometry/tangents-to-two-circles.md
Parens should not be escaped, `\(` and `\)` are math delimiters.
> Fix in tangents-to-two-circles, removing escaped parentheses

- src/graph/hld.md
There is a small mistake in the inequality sign in line 28 of Heavy-light Decomposition article. Fixed that!
> Fixed typo in Heavy-light decomposition

- src/algebra/discrete-root.md
In line 89: the condition was " != 1", but it should be " == 1" because if it is equal one then ok will be false (as res isn't primitive root) and will search for another primitive root.
Here is a simple test for this change:
A test inputs 11 2 4 (meaning x^2 = 4 (mod 11))
x is obviously 2 and 9.
Here is the correct output (after this modification: https://ideone.com/yFrWSc
Here is the incorrect output (before this modification): https://ideone.com/EeUVHI
> Fix condition in line 89 in discrete-root.md

- src/data_structures/disjoint_set_union.md
Without " <= ", function find_set( int ) would go into infinite recursion, since we need parent[ L ] to be equal to L.
> Fixed a bug in implementation

- src/graph/dinic.md
Would like to propose this change as emplace_back is a bit fast than push_back and avoids temporary variable creation.
> Use emplace_back instead of push_back

- src/num_methods/roots_newton.md
I understood the [original article](http://e-maxx.ru/algo/roots_newton) in Russian also used sqrt as the function for calculating the square root. However, I think the correct function here should be x^2 instead, and it is worth a correction.
> Update the function for calculating the square root

- src/algebra/fibonacci-numbers.md
Under section **fast doubling method**
The code should be above `The above code returns Fn and Fn+1 as a pair.`
Before:
After:
> fix incorrect position of code in fibonacci-numbers.md

- src/graph/bellman_ford.md
In the retrieving path section, the indentation in the break clause of bellman ford was misleading.
> Fixed an indentation error in bellman_ford.md

- css/common.css
On some pages like [this](https://cp-algorithms.com/graph/finding-cycle.html) one, the `pre` code block touches the footer.
As a simple fix, I added top and bottom margin of 16px for `pre` and top-margin of 16px for `#footer`. I chose 16px as the value because other elements like `p` and `ul` have same margins for them. So this would look consistent across the website.
> Fix for issue #461

- src/graph/bellman_ford.md
I ran ```test.sh``` and found a bug of the current spfa implementation.
```
In file included from test_spfa.cpp:7:
spfa.h: In function ‘bool spfa(int, std::vector<int>&)’:
spfa.h:35:1: warning: control reaches end of non-void function [-Wreturn-type]
35 | }
| ^
44 / 44 tests were successful.
```
It's a bool function that returns false if it detects negative cycle.
However, it has no "return true;" statement at the end of function.
If there is no negative cycle, the return value is uncertain.
> Added return statement in the code of spfa

- src/string/suffix-automaton.md
[This problem](https://codeforces.com/contest/128/problem/B) is essentially finding the k-th (in the lexicographical order) substring of the given string, but with duplicates allowed (which is different from the example in the article).
For example, given string `aa` (first test case), the lexicographically ordered list of all substrings is `a`, `a`, `aa`.
In the article, only first occurence of `a` counts, so the second one would be removed. However, with some modifications we can still solve this problem with Suffix Automaton.
I can provide my solution in C++ if needed.
Thank you!
> Add practice problem for Suffix Automaton

- src/algebra/fft.md
We are looking at a range of coefficients, not only 3. Hence, I added dots to make it clearer. I also make the word coefficient plural.
> Fixed typo in FFT

- src/algebra/sieve-of-eratosthenes.md
This pull request add implementation of segmented sieve, which generate all prime numbers in segment [L, R] where R is very large, but it's still possible to create an array of R - L + 1 elements.
I provide two implementation, one longer but faster, one shorter but slower. Both run under 0.1s.
Benchmark of both implementation is [here](https://ideone.com/cNjceF)
I have also tested my implementation on SPOJ problem [Prime Generator](https://www.spoj.com/problems/PRIME1/)
> Add segmented sieve

- src/graph/bridge-searching-online.md
Since we are adding 'b' instead of the 2-edge-connected representative of 'b', it may be possible that we will count extra bridges (to be deleted) than actual.
More details: https://discuss.codechef.com/t/ac-on-one-platform-rejected-on-another-and-vice-versa/66410
> Update bridge searching online

- src/graph/lca.md
Segment tree preprocess time is NlogN right? There are logN levels each of size N. Unless I am missing something :P
> Add sparse table option in LCA

- src/index.md
The [Prefix function](./string/prefix-function.html) article's name in `index.md` should also mention the name "Knuth-Morris-Pratt" as this is the name by which algorithm is rather popular. Otherwise, it is difficult to find the article for those looking solely for KMP.
> Mentioned Knuth-Morris-Pratt in index.md

- src/string/manacher.md
The bullet points were not rendering in markdown as there should be a blank line before creating bullets. Added blank lines on 2 instances.
> Corrected rendering of bullet points

- src/string/aho_corasick.md
Fixed a small typo.
Under construction of a trie, changed "mush" to "must"
> Fixed a typo in Aho-Corasick

- src/string/aho_corasick.md
This more clearly reflects the lines of code 
```cpp
if (v == 0 || t[v].p == 0)
t[v].link = 0;
```
I think it's clear that the suffix link of the root is the root, but it was less clear to me at first that the suffix link of the children of the root was the root from reading the explanation alone.
> clearer explanation of base cases for suffix links

- src/graph/Assignment-problem-min-flow.md
push_back() is no method of std::queue. We use push() instead of it.
> Minor debugging in implementation of Assignment-problem-min-flow.

- src/graph/finding-cycle.md
The previous algorithm used a vector of char to maintain vertex state. But in fact a vector of bool is sufficient here. Update the DFS. And stop setting vertex state when the DFS leaves a vertex, this is unnecessary.
> Simplify dfs to find cycle for undirected graphs.

- src/graph/hld.md
The decompose function does not return anything, so changed from 'int' to 'void'.
> Changed the return type of 'decompose' function

- src/schedules/schedule_one_machine.md
Use of comma before _that_ is not necessary rather it is worsening the reading experience of a reader
> Unnecessary comma is removed

- src/graph/2SAT.md
The `order` vector needs to be cleared when `solve_2SAT` is called.
The current code does take care of resetting `used` and `comp` vectors so it is only fair that `order` vector gets reset too.
> fix missing clear on order vector

- .gitignore
- src/dynamic_programming/divide-and-conquer-dp.md
- test/test.sh
- test/test_divide_and_conquer_dp.cpp
This PR reverts the incorrectly fixed typo in https://github.com/e-maxx-eng/e-maxx-eng/pull/402/commits/d0082f4860f346fffaaeefeeecb446d632a5026d as part of PR https://github.com/e-maxx-eng/e-maxx-eng/pull/402.
Doing ```best = min(best, {dp_before[k] + C(k, mid), k});``` is just wrong, because here both segments overlap as they are inclusive. But overlapping is not allowed as an element can belong to at most one partition. https://github.com/e-maxx-eng/e-maxx-eng/pull/712/commits/e134b20905bb960c6e77209fa85ad7d2e4c44b6f should fix it.
This snippet didn't have any tests. As a result, the incorrectly fixed typo got undetected for more than two years! So added tests to prevent such scenarios from happening in the first place going forward.
While running the tests locally, I noticed that as …
> Fix Divide And Conquer DP

- src/combinatorics/bracket_sequences.md
- src/geometry/convex_hull_trick.md
- test/test.sh
- test/test_lichaotree.cpp
Follow up from https://github.com/e-maxx-eng/e-maxx-eng/pull/712#issuecomment-852346731
This PR fixes two occurrences of undefined behavior in https://github.com/e-maxx-eng/e-maxx-eng/pull/713/commits/f45815dbfc45043a0362a546a2c995c522170972 and https://github.com/e-maxx-eng/e-maxx-eng/pull/713/commits/a05462f87515b0bb214deeb8213346186b5cfec2.
Then, https://github.com/e-maxx-eng/e-maxx-eng/pull/713/commits/01bb5e649d7fe2bfb8338e3f1d953ba73c8da45d updates the test runner to run with ```-fsanitize=undefined -fno-sanitize-recover```. This should enable checking for undefined behavior and exit with a non-zero status code. Thereby preventing scenarios where undefined behavior is mistakenly introduced.
> Fix undefined behavior

- src/algebra/factorial-modulo.md
> Fix typo in Factorial modulo

- src/graph/strongly-connected-components.md
The condensation graph code used 
`adj_scc[root_v].insert(root_u)`
When it should've been 
`adj_scc[root_v].push_back(root_u)`
> Corrected typo in condensation graph code

- src/_templates/default.html
- src/string/suffix-array.md
MathJax is having a hard time to convert `\\$`.  This change config MathJax to
process escape, and fix the usage of escaped dollar-sign in the document.
> Fix tex on suffix-array page

- src/algebra/fft.md
Fixes typo in fft.md 
[https://hal.archives-ouvertes.fr/hal-02070778v2/document](url)
> fixes typo in fft.md

- src/algebra/binary-exp.md
There is a typo in Binary Exponentiation, section Implementation
It should be `Although the complexity of both approaches is identical, this approach will be faster in practice since we **don't** have the overhead of the recursive calls.` instead of `Although the complexity of both approaches is identical, this approach will be faster in practice since we have the overhead of the recursive calls.`
> Fixes typo in binary-exp.md

- src/data_structures/segment_tree.md
`1+2+4+...2^ceil(log_2(n))` is less than `2^(ceil(log_2(n))+1)`
E.g. `n=5`, left side is `1+2+4+8=15`, and right side is `2^(3+1)=16`
> Fix typo with size estimation for segment tree (#1)

- src/data_structures/stack_queue_modification.md
An extra level of inline math nesting using ```$``` is rendering ```\( ... \)``` on the website.
> Remove redundant inline math nesting

- src/algebra/phi-function.md
The loop already sets `phi[i] = i` so no need to set phi[0] and phi[1] manually.
> Simplify code for calculating phi for 1..n

- src/algebra/factorization.md
- src/combinatorics/inclusion-exclusion.md
- src/game_theory/sprague-grundy-nim.md
- src/geometry/delaunay.md
- src/geometry/halfplane-intersection.md
- src/geometry/minkowski.md
- src/graph/all-pair-shortest-path-floyd-warshall.md
- src/graph/edmonds_karp.md
- src/graph/mpm.md
- src/graph/second_best_mst.md
- src/string/aho_corasick.md
- src/string/prefix-function.md
- src/string/suffix-automaton.md
This is the same thing as
https://github.com/e-maxx-eng/e-maxx-eng/pull/801
I searched for all instances of `\\{` and changed all but one.
There is an instance in the D&C DP chapter that I think looks better without the curly braces.
> Make some double-escaped curly braces single-escaped

- src/graph/kuhn_maximum_bipartite_matching.md
Added a note about using MCBM algorithms to find the cardinality of the minimum vertex cover for bipartite graphs (Kőnig's theorem).  Also added two practice problems from Kattis.
> Added MCBM practice problems and vertex cover note

- src/data_structures/sparse-table.md
The variable name `log` causes an error as `log` is already defined.
Changed the name to lg so you can just directly copy paste the code without having to change the variable names manually.
> Renamed log[] to lg[] to prevent ambiguous error in sparse table

- src/string/manacher.md
The previous assignment of the "l" and "r" variables lead to out of bounds access of array p, which is cancelled out by subsequent operations, but still triggers undefined behavior
> Fixing assignment of variables "l" and "r"

- src/string/suffix-tree-ukkonen.md
Image quality isn't the greatest but its the best (legal) source I could find. Continuation from #895.
> Fix broken link in Suffix Tree Article

- src/algebra/factorial-divisors.md
As discussed in #886, using `data-toc-label` will still render latex on the main page but it ignore in ToC.
> fix: latex rendering in ToC with data-toc-label

- src/graph/finding-cycle.md
When finding a cycle in an undirected graph, one doesn't have to reverse the cycle before printing it.
> Remove unnecessary reversal in finding-cycle algo

- src/algebra/polynomial.md
Seems like some LaTeX-like engine disagrees with LaTeX about what is an atom.
LaTeX parses `a^\cmd{x}{y}` as `{a^\cmd{x}}{y}`, rather than `a^{\cmd{x}{y}}` which is what's intended here.
> Fix malformed LaTeX in polynomial.md.

- src/algebra/continued-fractions.md
The original code gives runtime error on `n = 3`. The updated code was tested on [Tavrida NU Akai Contest - Continued Fraction](https://timus.online/problem.aspx?space=1&num=1814).
> fix continued fraction sqrt code

- src/num_methods/binary_search.md
Change `f(y) = x` to `f(x) = y`
> Fix typo in intermediate value theorem

- src/algebra/fibonacci-numbers.md
As mentioned in my [issue](https://github.com/e-maxx-eng/e-maxx-eng/issues/976#issue-1496329595), the proof made an assumption that $F_0$ would be in the pre period which was incorrect so I changed that, and added some more explanation as to why the proof was sufficient.
> Corrected the proof that fibonacci numbers are periodic

- src/data_structures/segment_tree.md
Fix typo on segment tree page. Changing "free" to "tree".
> Fix typo on segment tree page. Changing "free" to "tree".

- src/algebra/module-inverse.md
- test/test_modular_inverse.cpp
The current explanation only focuses on its usage for pre-computing inverse for every number within [1, m-1] but this technique can also be efficiently (and most importantly, in a very simple manner) used to compute the inverse for a single number. Therefore, I want to update the doc to emphasize it better.
> Update modular inverse using Euclidean Division.

- src/algebra/chinese-remainder-theorem.md
p_i should only be used for primes, while CRT works for any coprime m_i (esp. case of prime powers p^e)
Feel free to come up with a more informative commit msg. I'm tired
> Replace p with m notation

- src/algebra/garners-algorithm.md
Visually the two spaces are not so different, but I ran into trouble while compiling this repo into TeX->PDF. Moreover, standardizing space usage is probably a good (but minor) thing in the long run.
I only found these 7 occurrences of non-standard spaces in the entire repo.
> Replace Unicode hair spaces in Garner’s Algorithm with regular spaces

- src/data_structures/segment_tree.md
The condition `l < tl` and `tr < r` will never be true in `query()`. So only `==` can be checked.
> Inconsistent inequality in segment_tree.md

- src/graph/search-for-connected-components.md
Variable in the loop in the code for search connected components is supposed to be v, not i
> Fix wrong variable names in connected components

- src/string/suffix-automaton.md
With change lcs method actually compiles and runs.
> Change .length to .len  as suffix automaton struct uses .len attribute

- src/algebra/linear_congruence_equation.md
This change resolves issue #1069 by changing the equal sign to congruence.
Signed-off-by: Sundaram krishnan <krishnsundaram@gmail.com>
> added congruence symbol to linear_congruence_equation

- src/game_theory/sprague-grundy-nim.md
Changed "number of its leading (biggest value) non-zero bit" to "index of its leading (biggest value) non-zero bit" as latter is clearer in its intention. I believe I am not the only one who got confused by whether "number of a bit" is referring to $2^(d-1)$ (i.e. the actual value of the bit) or $d$
> Change "number of ... bit" to  "index of ... bit"

- src/data_structures/segment_tree.md
- src/sequences/longest_increasing_subsequence.md
This might be controversial, but personally I don't really like the name "implicit" and the use might stem from competitive programming tunnel vision. In fact, the usual array-backed segment trees are [implicit](https://en.wikipedia.org/wiki/Implicit_data_structure) as they use a [specific layout](https://en.algorithmica.org/hpc/data-structures/segment-trees/#implicit-segment-trees) rather than pointers to navigate the tree. It also seems the name "dynamic" [is more popular already](https://codeforces.com/blog/entry/99074).
> Rename "implicit" to "dynamic" segment tree

- src/algebra/primality_tests.md
Integers less than 2 are not prime. I got a wrong answer because I copied this on a contest once. This corrects the error.
> Integers less than 2 (especially 1) are not prime.

- src/string/string-hashing.md
Wasn't sure why we used set rather than unordered_set to store unique hashes. This should lower the runtime from O(n^2*log(n)) to O(n^2).
> change set to unordered_set making distinct substrings O(n^2)

- src/combinatorics/bracket_sequences.md
A minor spelling mistake in balanced bracket sequences (balance validation)
> than —> then (balanced bracket sequences, balance validation)

- src/algebra/binary-exp.md
Refactor variable name to align with written description. The previous name (`b`) seemed very confusing because it was referenced in the description as `k`.
> Refactor variable name

- src/string/suffix-automaton.md
More thorough explanation of  "All occurrences positions" algorithm. answer(P) was never defined.  I think it may make sense to replace it with a singular variable like z or ans or something.
> Update suffix-automaton.md - No definition of answer(P)

- README.md
- Used the GitHub Workflow Status badge from shields.io
- Documentation can be found here - https://shields.io/badges/git-hub-workflow-status-with-event
> Fixed `build` badge on the home page

- src/data_structures/segment_tree.md
Ensure that each node stores the maximum of its children. Otherwise the results of any query will be wrong, unless this node has been visited by an "update" query previously.
> Add "build" function to segment_tree.md

- src/geometry/convex-hull.md
This PR addresses the situation where the convex hull consists of two identical points and the hull is strictly convex (i.e., collinear points are not included).
> Handle the degenerate case of convex hull consists of two identical points

- src/overrides/partials/content.html
* Currently it is possible that the interpolation escapes the confines of the quotes
* Also in a future version of MkDocs, values will become escaped by default, so this value will become incorrect under the current approach
---
As a specific example, currently the interpolation is:
```js
`Problem on article "Integration by Simpson's formula"`
```
(easy to hack it by inserting a character such as <code>`</code> or <code>$</code>)
In a future version of MkDocs this will become wrong:
```js
`Problem on article "Integration by Simpson&#39;s formula"`
```
I am changing it to:
```js
"Problem on article " + "Integration by Simpson\u0027s formula"
```
> Safely interpolate the page title into the "report issue" button

- mkdocs.yml
The mkdocs-material theme has the [`content.code.copy`](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=cod#code-copy-button) feature from the version `9.0.0`. This will help in copying the code-blocks more easily. As there are many places where **code-blocks/code-snippets** are present I think this would be quite useful.
I added the feature to [mkdocs.yml](https://github.com/cp-algorithms/cp-algorithms/blob/master/mkdocs.yml) and tested it locally using `mkdocs serve`. I am pasting the screenshots here to show the difference.
**Before**
**After adding the `content.code.copy` feature** (We can see the copy button at the top-right corner of the code-block)
Closes #1253
> feat: Added an existing feature of `mkdocs-material` that allows users to copy the `code-blocks/snippets` directly.

- src/string/aho_corasick.md
Tiny changes from `can be creating using` to `can be created using`.
> Fix typo in Aho-corasick page

- src/graph/depth-first-search.md
The reasoning for why forward and cross edges don't exist in undirected graphs stumped me when I was first learning graph theory from the wiki. Hoping to add this to help bring some intuition for future students and expand upon your guys' great work!
> Added proof of DFS edge classification in undirected graphs

- src/graph/bridge-searching.md
- test/test_bridge_searching_offline.cpp
Solves the issue https://github.com/cp-algorithms/cp-algorithms/issues/959 . As the original author has not shown any activity we created this PR.
> Fix bug in case of multiple edges in Finding Bridges offline

- src/data_structures/fenwick.md
The range operations are mentioned earlier on in the markdown file as follows:
> Point Update and Range Query
> Range Update and Point Query
> Range Update and Range Query
All the actual section/subsection titles stay consistent with this list except for the third one (which is instead "Range Updates and Range Queries").
> Improve title consistency in fenwick.md

- src/graph/2SAT.md
- test/test_2sat.cpp
The existing code didn't work out of the box, and `n` was used for both the number of variables and the number of vertices in the graph.
> Fix 2SAT.md

- mkdocs.yml
As of recently, the service polyfill io is no longer trustworthy as it has [been used to inject malicious code into websites](https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet). To address the security concern the CDN was modified to the cloudflare mirror.
> Change to cloudflare CDN for polyfill io

- src/combinatorics/bracket_sequences.md
Hello, while reading the article I encountered some typos: Here is the list:
needs to be changes -> needs to be changed
each pair be -> each pair can be
If we find do suitable position -> If we don't find a suitable position can be generate -> can be generated
We will us -> We will use
change is we have -> change if we have
In each position we have to decide if we use an opening of a closing bracket. -> At each position, we have to decide whether to place an opening or a closing bracket.
To have to put an opening bracket character, it $d[2n - i - 1][\text{depth}+1] \ge k$ . -> To place an opening bracket, $d[2n - i - 1][\text{depth}+1] \ge k$ must be true.
We increment the counter -> If so, we increment the counter
and try to put this bracket -> and try to place this bracket
> fixing typos in bracket_sequences.md

- src/graph/finding-negative-cycle-in-graph.md
The information is taken from the [Bellman-Ford](https://cp-algorithms.com/graph/bellman_ford.html) page. I felt it should be present here as well to make this article self-sufficient.
Also modified the code to remove the redundant check since `d` is initialised to `0` instead of `INF` so the check is not required.
> Added more information in finding negative cycle using Bellman-Ford

- src/game_theory/sprague-grundy-nim.md
They mention in [the editorial](https://atcoder.jp/contests/abc368/editorial/10829) that problem [ABC368 - F - Dividing Game](https://atcoder.jp/contests/abc368/tasks/abc368_f) is related to the Grundy theorem. So I add it into the practice problem section.
> Add a practice problem for the Grundy theorem

- src/graph/strongly-connected-components.md
sort(component.begin(), component.end()) is linearithmic, which breaks the expected linear complexity of Kosaraju. Line is also superfluous and unnecesary.
> Remove components sort, Kosaraju should be O(n)

- test/test_divide_and_conquer_dp.cpp
Fixed the typo "occurence" -> "occurrence", in a comment.
> Fix typo in a comment: "occurence" -> "occurrence"

- src/graph/breadth-first-search.md
The current code can't find a path of even length from a source vertex s to a target vertex t. But, it can find a walk of even length
Referenced issue:
Possible error in Shortest even length path (Applications of BFS) #1257
> Fixes example in breadth-first-search.md

- src/geometry/convex-hull.md
- src/num_methods/simpson-integration.md
In the articles, there are two links to problems from URI Online Judge, which has changed to [beecrowd](https://judge.beecrowd.com/en). Therefore, those links are now broken, because they always redirect to [this page](https://beecrowd.com/), which does not show any problem, and is not even part of the actual beecrowd online judge system.
So, this PR updates the links to those two problems.
Please notice that it is still necessary to log in to beecrowd before viewing the problem.
> Fix beecrowd problems hyperlinks

- src/graph/dinic.md
These two lines check a condition that is already checked in the for loop and can safely be removed. The test.sh file was also executed 
Referenced issue: 
Redundant check in dfs of dinic #1344
> Removes redundant check from dinic's dfs

- src/dynamic_programming/knapsack.md
The existing groups are: $2^0, 2^1, \dots, 2^{\lfloor \log_2(k+1) \rfloor - 1}$ and they sum up to $2^{\lfloor \log_2(k+1) \rfloor} - 1$. So, the remaining groups should be $k_i - sum$.
> Fix the remainder group size in binary grouping solution of the multiple knapsack problem

- src/geometry/planar.md
- test/test_planar_faces.cpp
Current check for a polygon order is incorrect, and it breaks on the following test:
Here's the code that generates this test:
```c++
vector<Point> pts = {{0, 2}, {1, 3}, {0, 1}, {1, 0}, {-1, 0}, {-1, 3}};
vector<vector<size_t>> adj(pts.size());
auto add_edge = [&](int u, int v) {
adj[u].push_back(v);
adj[v].push_back(u);
};
add_edge(0, 1);
add_edge(1, 2);
add_edge(2, 3);
add_edge(3, 4);
add_edge(4, 5);
add_edge(5, 0);
```
For an outer face (1→2→3→4→5→0), the previous version of the algorithm would first check the triplet 1→2→3. Since this triplet is ordered in counter-clockwise order, it would incorrectly mark this face as inner.
So, instead we should use something different. I used the oriented area, however, since the coordinates are stored as int64_t, I had to use __int128, which …
> Bug in the face order check

- src/algebra/fibonacci-numbers.md
Maybe a dotted line would show the matrix [[F2, F1],[F1,F0]] can be viewed as two column vectors. Using only the matrix power saves one matrix-vector multiply. Related #1453
> Fibonacci: restore matrix power form

- src/geometry/basic-geometry.md
> To see the next important property we should take a look at the set of points $\mathbf r$ for which $\mathbf r\cdot \mathbf a = C$ for some fixed constant $C$.
You can see that this set of points is exactly the set of points for which the projection onto $\mathbf a$ is the point $C \cdot \dfrac{\mathbf a}{|\mathbf a|}$ and they form a hyperplane orthogonal to $\mathbf a$.
I guess for $\mathbf r\cdot \mathbf a = C$ the point of projection is $\mathbf r \cos \theta$ which is of magnitude $C/|\mathbf a|$ and has direction of $\hat{a}$ (unit vec along ${\mathbf a}$) so the point is $C \cdot \dfrac{ \hat{\mathbf{a}}}{|\mathbf a|}$ which evaluates to  the point $C \cdot \dfrac{\mathbf a}{|\mathbf a|^2}$
> small modification in basic geometry dot product

- src/graph/bridge-searching-online.md
The original text stated that the number of bridges decreases by “two or more,” which is incorrect in some cases. 
For example, in this graph:
1-2-3-1
3-4
4-5-6-4
There is one bridge (3–4). Adding an edge between 1 and 4 removes only that single bridge.
This change updates the text to say “one or more,” which is accurate in all cases.
> docs: fix bridge count wording to "one or more" in bridge-searching-online.md

- src/dynamic_programming/knuth-optimization.md
This PR updates the documentation to clarify the definition of `opt(i, j)`:
- Previously, it was ambiguous when multiple values of `k` achieved the optimum.  
- The reference explicitly states that we should take the **maximum** value of `k` among all optimal candidates.  
- This change makes the intended behavior explicit and avoids confusion in implementations.  
Clarifying this definition ensures consistency with the reference and prevents misinterpretation when different values of `k` yield the same optimum.  
- Clarified wording in `opt(i, j)` definition.  
- Specified that the chosen `k` must be the maximum among all optimal candidates.  
> The reference is https://dl.acm.org/doi/pdf/10.1145/800141.804691, specifically, when we define $K_c$ on the left column, the reference make it …
> Clarify definition of opt(i, j): choose maximum k among optimal candidates
