src/mypage.md

Hi guys, please merge this into our site!

Creating simple test page

---

src/geometry/circle-circle-intersection.md
src/index.md

I've added "Practice Problems" section, which I feel is useful but missing in original e-maxx article.

Add 'Circle-circle intersection' article

---

src/geometry/circle-circle-intersection.md

Hi,
I have added 2 practice problems to the circle-circle intersection article. I suppose the problems are interesting and good for practice, below are the links as well.
[Runaway to a shadow - Codeforces](http://codeforces.com/problemset/problem/681/E)
[ASC 1 Problem F "Get out!"](http://codeforces.com/gym/100199/problem/F)

Added problems to circle-circle intersection article

---

src/data_structures/fenwick.md

Added Practice problems, UVA -12086,, LOJ-1112, LOJ-1266

Added Practice problem for Fenwick Tree.

---

src/contrib.md

The other link was going to a 404 page for me

fix link to repository in contrib.md

---

src/algebra/binary-exp.md

Here are some practice problems from the Uva OJ. They may also use Modular Arithmetic!

Added practice problems for binary exponentiation

---

src/algebra/chinese-remainder-theorem.md

Practice problem from Hackerrank contest which uses only Chinese Remainder Theorem!

Added problem for Chinese Remainder Theorem

---

src/data_structures/fenwick.md

Practice problems from SPOJ and codechef

Added practice problems for Fenwick Tree

---

src/string/suffix-array.md

Practice problems from UVA OJ for Suffix Array

Added practice problems for Suffix Array

---

src/graph/all-pair-shortest-path-floyd-warshall.md
src/index.md

Please feel free to suggest improvements.

Translated Floyd-Warshall

---

src/string/string-hashing.md

Changed ni-1 to n-i so that every hashes have same degree.

Simple correction

---

src/combinatorics/binomial-coefficients.md
src/index.md

Add the Binomial Coefficients article

add Binomial Coefficients

---

src/graph/dijkstra.md

Please feel free to suggest improvements.

Translated Dijkstra single source shortest path

---

src/algebra/all-submasks.md

In the last commit of this file I made a huge mistake.
I added problems that require bitmask to solve, but most of them have nothing to do with submask enumeration.
I 'm sorry for my carelessness, replacing those problems with ones that can really be solved with submask enumeration.

Update Submask Enumeration practice problems

---

src/graph/mst_kruskal.md

Very Sorry @RodionGork ... My bad!! I have corrected formatting errors as you had suggested...
Once again.. very sorry for wasting you precious time mate... I am attaching a screenshot of test page. Hope it helps:

Corrected Formatting MST Kruskal O(MlogN+N^2) 

---

src/graph/mst_kruskal_with_dsu.md

Once again I'm really sorry @RodionGork ... I've corrected the formatting for this article. I'm attaching a screenshot of the test page here...

Corrected Formatting MST Kruskal DSU O(MlogN)

---

src/graph/all-pair-shortest-path-floyd-warshall.md

Hey @RodionGork .. I was just going through this article on e-maxx-eng and saw some typos.. Again the formatting was not proper because of lack of use of Mathjax so I've fixed those...

Fixed Typos and Mathjax in Floyd-Warshall

---

src/combinatorics/catalan-numbers.md

Added translation for Catalan numbers, along with some insights for better understanding. 
Practice problems also added.

Added catalan numbers

---

src/graph/topological-sort.md

Add classic practice problem for topological sorting

Add classic practice problem for topological sorting

---

src/combinatorics/catalan-numbers.md

Added the FUNPROB from SPOJ. This problem requires the catalan number for derivation of its formula. It is an quite interesting problem on Catalan number to start with.

Added the practice problem for Catalan Number

---

src/graph/bellman_ford.md

Please feel free to suggest improvements...

Translated Bellman-Ford

---

src/graph/strongly-connected-components.md

Just fixing some typos of "Finding strongly connected components
Building condensation graph" .

Fixing typos

---

src/graph/search-for-connected-components.md

Improvements in the formulas and notations and also code spacing.

Improved article "Search for connected components"

---

src/algebra/binary-exp.md

Some small improvements in the formulas and the code spacing.

Improvements in Binary Exponentiation

---

src/graph/dijkstra.md

A Problem added to Dijkstra :)

Problem added to Dijkstra

---

src/graph/breadth-first-search.md

Added new  problem

---

LICENSE

This seems to be the most fitting license, since our project contains educational material and not software per se.
This closes issue #61.

Add CC BY-SA license to the project

---

src/index.md
src/schedules/schedule-with-completion-duration.md

This change resolves conflicts in #149 so that it can be merged.

Merging #149

---

src/data_structures/sqrt_decomposition.md
src/index.md

Based on work by https://github.com/vgupta3

Sqrt decomposition with formulas instead of images

---

src/contrib.md

@tcNickolas Hi! This PR is mainly to make sure you will notice this subtle change. The main idea is that now participants can propose (if there is utter necessity) changes to the template in this repo (previously this required re-uploading the whole app which only I was able to do, and I also didn't remember the process well).
Regretfully templates could not be tested (e.g. with test-your-page) beforehand by participants, so it's ok to merge them, and if anything is broken, revert back. %)
Though I hope it will not be very common :)
_Respective change in e-maxx-eng-auto was merged here https://github.com/e-maxx-eng/e-maxx-eng-auto/pull/5 though I hope no one will need to bother with this nasty code_

Explanation about templates in the repo

---

src/algebra/phi-function.md

+ N = 22 removed to avoid scroll
+ general multiplicity

General Euler Theorem added

---

src/data_structures/sqrt-tree.md
src/index.md

It is the data structure to compute any operation on a segment in O(1) time with O(NloglogN) preprocessing. See http://codeforces.com/blog/entry/57046.

Added Sqrt-tree

---

src/index.md
src/string/manacher.md

Manacher algorithm was translated from e-maxx. The source code was adjusted to work correctly. Also there is code style fixes.

Manacher algorithm added

---

src/data_structures/disjoint_set_union.md
src/graph/mst_kruskal.md
src/graph/mst_kruskal_with_dsu.md

DSU improvement

---

src/combinatorics/generating_combinations.md
src/index.md
test/test_generate_combinations.cpp

Hello, I've added the "Generating Combinations" article pending under the "Combinations" section - http://e-maxx.ru/algo/generating_combinations
And I've added the article to the index as well.
Let me know if I've missed anything!
Thanks!

Add "Generating Combinations"

---

README.md
src/geometry/grahams-scan-convex-hull.md
src/index.md
test/text_graham_scan.cpp

Hi!
I've translated Convex Hull Construction using Graham's Scan - http://e-maxx.ru/algo/convex_hull_graham
I've added the title to the index too.

Translate "Graham's Scan" article

---

src/graph/lca.md
test/test_lca.cpp

I updated the code of the LCA, it is basically the same code than before but I changed the style (in order to match the recent codes) and put everything inside a struct to make the testing easier. I also added one test for the code.
I also tested the code with the problem [LCA - Lowest Common Ancestor](https://www.spoj.com/problems/LCA/)

update LCA code

---

src/algebra/linear-diophantine-equation.md
test/test_linear_diophantine.cpp

Hi!
I found an error in the code "finding the number of solutions" of the article "Linear Diophantine Equations". I also added new tests for this code since they were missing.

fix code for linear diophantine equation

---

src/data_structures/sqrt-tree.md

Added parts of the article describing updates on Sqrt Tree (single element and on segment). Code is changed to support single element updates.

Added info about the updates in the Sqrt Tree

---

src/algebra/balanced-ternary.md
src/algebra/big-integer.md
src/algebra/euclid-algorithm.md
src/algebra/extended-euclid-algorithm.md
src/algebra/fft.md
src/algebra/fibonacci-numbers.md
src/algebra/gray-code.md
src/algebra/module-inverse.md
src/algebra/phi-function.md
src/algebra/primitive-root.md
src/algebra/sieve-of-eratosthenes.md
src/combinatorics/inclusion-exclusion.md
src/data_structures/sparse-table.md
src/data_structures/sqrt-tree.md
src/data_structures/sqrt_decomposition.md
src/data_structures/treap.md
src/geometry/area-of-simple-polygon.md
src/geometry/lines-intersection.md
src/graph/all-pair-shortest-path-floyd-warshall.md
src/graph/bridge-searching-online.md
src/graph/strongly-connected-components.md
src/num_methods/ternary_search.md
src/string/suffix-array.md
src/string/z-function.md

In the process of getting these documents to compile these into a pdf-book I encountered quite a few things that had to be fixed to work with both the markdown converter used here and pandoc's LaTeX converter. Initially written as countless regexes to patch everything, I've now went through and fixed everything the regexes would have targeted and more. For substantial changes I've been careful to check that the converter used here produced correct output.
While these are quite widespread edits, they are separated into several categorized commits that should be quite digestable.
Edit: I might have screwed up rebasing stuff since commit 7f72ab3 now looks a bit weird, not sure how to easily fix that

Overall fixes

---

src/data_structures/fenwick.md

Changing minor inconsistency in *Fenwick tree* article

Minor change in fenwick.md

---

README.md
src/combinatorics/generating_combinations.md
src/contrib.md
src/graph/strongly-connected-components.md

update old links (http://e-maxx-eng.appspot.com) with (https://cp-algorithms.com)

update old links

---

src/dynamic_programming/zero_matrix.md
src/index.md

I wrote the zero submatrix problem. Please, make a review before accepting the pull request. Thank you, I hope everything is all right.

Zero matrix branch

---

src/graph/2SAT.md

I added the practice problems and finding more problems.

Updated 2SAT probs

---

src/linear_algebra/linear-system-gauss.md

added a practice problem and finding more

Updated practice problems

---

src/graph/bridge-searching.md

added a UVA Problem to practice problems

Updated with prac problems

---

src/graph/2SAT.md

found one more practice problem

updated 2SAT prac probs

---

src/algebra/sieve-of-eratosthenes.md

Changed is_prime[j] = true to is_prime[j] = false

Corrected a typo in the block sieve code

---

README.md
src/algebra/sieve-of-eratosthenes.md
src/num_methods/simpson-integration.md

1. Fixed for loop control iterator.
2. Fixed minor syntax errors.
3. Optimized the ternary operation by removing a redundant check.

Fixed bugs in Simpson's Formula

---

src/graph/euler_path.md
src/index.md

Finding a Eulerian path or Eulerian cycle is O (M)

Translated Euler path

---

src/algebra/module-inverse.md
src/combinatorics/binomial-coefficients.md

For issue #310 
"Binomial coefficients modulo m" moved to binomial-coefficients.md.
Some new content added to the section.

Relocation of "Binomial coefficients modulo m"

---

src/data_structures/sqrt_decomposition.md

Fix in comparison function for sorting.

Minor but crucial bug fix in Mo's algorithm

---

src/geometry/intersecting_segments.md
src/graph/euler_path.md
src/graph/tree_painting.md
src/others/maximum_average_segment.md

Add some missing language annotations to code fences

Add language to code fences

---

src/geometry/segment-to-line.md
src/index.md

Added the translation for this [page](http://e-maxx.ru/algo/segment_to_line).

Translated Finding the equation of a line for a segment

---

src/algebra/chinese-remainder-theorem.md

The CRT article had badly formatted mathematics, which was bad in html and horrible in the pdf. Did quite a bit of clean-up of math and formatting, and rewrote parts of the article while I was going through it.

Major clean-up and minor rewrites of CRT

---

src/algebra/fibonacci-numbers.md
src/combinatorics/catalan-numbers.md
src/geometry/point-in-convex-polygon.md
src/geometry/point-location.md
src/graph/Assignment-problem-min-flow.md
src/graph/strongly-connected-components.md
src/linear_algebra/rank-matrix.md
src/num_methods/simpson-integration.md
src/sequences/k-th.md
src/string/suffix-array.md

Found these issues when I generated the PDF myself

Fixup headings

---

src/graph/lca_tarjan.md

One more I missed for last commit. It's amazing how much small issues you find when you actually start fixing warnings.

One more section depth fix

---

src/data_structures/disjoint_set_union.md
src/data_structures/fenwick.md

Changed the implementation and removed two unnecessary blockquotes.

 Minor changes in fenwick.md 

---

src/others/stern_brocot_tree_farey_sequences.md

A friend proofread the text and found some issues. N.B. editing tired is a bad idea.

Fix some errors in Stern-Brocot Farey

---

src/algebra/prime-sieve-linear.md
src/index.md

`Having` is the wrong tense to use here. 
One would say:
> I'm implementing the Eratosthenes Sieve with Linear Time Complexity
and not
> I'm implementing the Eratosthenes Sieve Having Linear Time Complexity

Changed name of the Linear Eratosthenes Sieve

---

src/string/prefix-function.md

fix mistake in prefix function.

---

src/data_structures/treap.md

Add section "Building a Treap in O(N) in offline mode"

---

src/string/suffix-automaton.md

ref: https://github.com/24OI/OI-wiki/issues/849
thanks to @partychicken and @LeoJacob
* * *
Hi, I've changed the expression in Lemma 3. You know, they can't be suffixes of each other....

fix: update expression in Lemma 3

---

src/algebra/fft.md
src/combinatorics/bracket_sequences.md
src/combinatorics/burnside.md
src/data_structures/disjoint_set_union.md
src/data_structures/segment_tree.md
src/data_structures/sqrt-tree.md
src/data_structures/sqrt_decomposition.md
src/graph/all-pair-shortest-path-floyd-warshall.md
src/graph/dijkstra_sparse.md
src/graph/edmonds_karp.md
src/graph/fixed_length_paths.md
src/graph/mst_kruskal.md
src/graph/mst_prim.md
src/schedules/schedule_two_machines.md
src/string/aho_corasick.md
src/string/expression_parsing.md
src/string/lyndon_factorization.md
src/string/string-hashing.md
src/string/suffix-automaton.md

`git grep -P '(?!.*long long)\b(\w+)\s+\1\b'`

Fix typos (repeated words)

---

src/algebra/discrete-log.md

Mainly editing, correcting mistakes and mathematical pedantry, but also some code style changes.  
I think the `ans < m` checks were unnecessary

Discrete log improvements

---

src/game_theory/sprague-grundy-nim.md
src/index.md

Only one example game translated

Add Sprague-Grundy and Nim

---

src/graph/second_best_mst.md

These kinds of minor PRs just feel silly to write.

Replace unicode minus with hyphen

---

src/algebra/primality_tests.md

Modified Miller-Rabin Primality Test to fix some bugs and commented a few code snippets.

Fixed bugs in primality_tests.md

---

src/graph/dijkstra_sparse.md

Two grammatical errors to be precise

update small grammar errors

---

src/graph/second_best_mst.md

Let me know if there are any formatting errors in the code added.

Added Implementation for computing Second Best MST

---

css/common.css

min-device-width is [deprecated](https://www.w3.org/TR/mediaqueries-4/#mf-deprecated)

Change min-device-width to min-width

---

src/graph/strong-orientation.md
src/index.md

https://en.wikipedia.org/wiki/Strong_orientation
AFAIK, there is no other public implementation of this (simple) algorithm on the internet

Add Strong Orientation

---

src/graph/dijkstra_sparse.md

Just corrected a single typo in a single md file.

Corrected typo in dijkstra_sparse.md

---

src/data_structures/stack_queue_modification.md

Corrected Code at 2 places (Line 147 and Line 160) and made sure it compiles without throwing any error.

Corrected C++ Syntax in stack_queue_modification.md

---

src/graph/kirchhoff-theorem.md

The page on Kirchhoff's Theorem mentions only two problems for practice. [This](https://www.codechef.com/problems/CSTREE) is the problem I added to extend the list.

Added one practice problem in kirchhoff-theorem.md

---

src/algebra/primitive-root.md

Just changed ... to more standard interval notation.

Update primitive root article to use more clear interval notation

---

src/algebra/fft.md
src/graph/kirchhoff-theorem.md

Modified a single line in a single file. Changed subscript from `{n_0}` to `{n, 0}`.

Fixed LaTeX typo in fft.md

---

src/graph/dijkstra_sparse.md

Fixed a typo in the time complexity

---

src/linear_algebra/rank-matrix.md

I made the changes discussed in the previous PR and added the problem I tested the code on.

Changed matrix rank a bit

---

src/linear_algebra/linear-system-gauss.md
src/linear_algebra/rank-matrix.md
test/test_gauss.cpp
test/test_rank_matrix.cpp

I've also added a couple of problems on Gauss method.
Btw, is there currently any way to create automatic tests for Java code? I want to test Kraut algorithm, but it is in Java.

Added some tests for linear algebra

---

src/data_structures/fenwick.md

Change inc to actual function name "increase" in Fenwick.md

Fixed typo - change from inc to increase

---

css/common.css

Please check the file changes.

Fixed a typo in common.css

---

src/data_structures/segment_tree.md

fix minor typo in segment tree.

---

src/graph/Assignment-problem-min-flow.md
src/graph/min_cost_flow.md
test/test_min_cost_flow.cpp

replace implementations of shortest path algotirhm in min cost flow and assignment problem with SPFA (#438)

Fixed issue #438

---

src/graph/tree_painting.md

This is very small, but I found.

fix a small typo

---

src/data_structures/disjoint_set_union.md

Hello admins, 
I have added a few interesting problems to disjoint_set_union.md file. Please merge this.

Added few problems to disjoint_set_union.md

---

src/algebra/all-submasks.md
src/algebra/linear_congruence_equation.md
src/game_theory/games_on_graphs.md

I've combed through 3 articles and tried to fix any grammatical or formatting errors I could find. The articles are -
I plan on doing this for all the other articles in due course.

Fix grammatical + formatting errors in 3 files

---

src/data_structures/disjoint_set_union.md

Hello admins,
I have fixed sentences in disjoint_set_union.md file. Please merge this.

Fixed sentences

---

src/combinatorics/inclusion-exclusion.md

Hi guys, this is my first pull request on github. Please review it.

Added another related problem.

---

src/data_structures/segment_tree.md

Added info about reducing memory consumption in recursive segment tree.

Segment tree new information.

---

src/algebra/phi-function.md

Added divisor sum and etf from 1 to n.

---

src/data_structures/sqrt_decomposition.md

Changed "out data structure" to "our data structure" in line 130

Fixed minor typo

---

src/graph/mst_kruskal.md

added question on mst

---

src/graph/breadth-first-search.md

The modified point explains the application in a better way.

modified the explanation of 4th application of BFS

---

src/algebra/factorial-modulo.md

Nitpick: algebra/factorial-modulo

---

src/string/aho_corasick.md

This problem came in the recent May Long Challenge 2020 of Codechef. [This](https://discuss.codechef.com/t/twostrs-editorial/64199) is its detailed editorial. I think it's a nice problem solved decently using Aho Corasick.

Add new problem in Aho Corasick

---

src/string/prefix-function.md

This problem is a nice, direct application of the "Counting the number of occurrences of each prefix" technique described earlier in this article.

Add KMP problem

---

src/string/string-hashing.md

Found some grammatical errors in https://github.com/e-maxx-eng/e-maxx-eng/blob/master/src/string/string-hashing.md and fixed it. Thank you.

Fixing string hashing grammatically.

---

src/algebra/fibonacci-numbers.md

Two practice problems on fast computing of fibonacci numbers from DMOJ.

Added two practice problems

---

src/algebra/discrete-log.md
test/test_discrete_log.cpp

- Add section for non-coprime a and m.
- Add tests.
- Make some adjustments to the existing text.
Closes #568.

Update the discrete log article

---

src/graph/bellman_ford.md

Improved language in last line of "Proof of Algorithm" part.

Improved language

---

src/data_structures/segment_tree.md

I felt that the explanation of construction is written in one single paragraph, twice over and it gets confusing.
(even though it is spaced in `.md` file, this is how it actually appears ^)
Moreover, there is no explanation of the `merge` function, which I feel is quite important to a complete understanding of a segtree.
In this PR, I have added details to the construction process, and made references to generic "value" and "merge operation" (instead of the focusing specifically on sum segtree)

Segment tree construction

---

src/graph/finding-cycle.md

I have added implementation for detecting and finding cycle in Undirected graph. I tried to make minimum changes to existing code and added comments at appropriate places to make it clear. Consider this Pull request in response to issue #387

Adding Implementation for Undirected-Graph as per #387

---

src/data_structures/disjoint_set_union.md
src/graph/finding-cycle.md

I have added a new practice problem on topic DSU. Also removed an old problem on the same topic as it was giving 404 NOT FOUND error at the link provided.

Updating a Practice problem and removing an old one(no longer available) on DSU

---

src/string/manacher.md

The link to the UVA problem was broken and added a link to a Codeforces GYM problem

fixing Manacher's problem link and adding another

---

src/graph/2SAT.md
src/graph/all-pair-shortest-path-floyd-warshall.md
src/graph/bellman_ford.md
src/graph/bipartite-check.md
src/graph/breadth-first-search.md
src/graph/dijkstra.md
src/graph/euler_path.md
src/graph/finding-cycle.md
src/graph/mst_kruskal.md
src/graph/search-for-connected-components.md
src/graph/strongly-connected-components.md
src/graph/topological-sort.md

Added cses problems to most of the graph section

added graph cses problems

---

src/string/manacher.md

- Minor grammatical corrections
- Missing keywords added for better understanding

Manacher: Missing keywords added for better understanding

---

src/string/manacher.md

Detailed explanations added so that understanding the code is easier.

Manacher code explanation added

---

src/data_structures/disjoint_set_union.md

small typo

---

src/string/string-hashing.md

Hello admins,
I have added a practice problem to **string-hashing.md** file. Please merge this.

Added a string-hashing practice problem

---

src/data_structures/treap.md
src/geometry/convex_hull_trick.md

Problems from Codeforces for:
* Convex Hull Trick
* Treap

New example problems

---

src/data_structures/disjoint_set_union.md

Just fixing a small typo in the article. No more, no less.

Disjoint-set union

---

src/dynamic_programming/divide-and-conquer-dp.md

It can be solved with the exact method in the article, so it might be a good starting point!

Added new problem for Divide+Conquer DP.

---

src/geometry/convex_hull_trick.md

https://dunjudge.me/analysis/problems/264/ -> APIO 2010 "Commando"
https://dunjudge.me/analysis/problems/896/ -> Dunjudge "Troubles"

Added practice problems for "Convex Hull Trick"

---

src/algebra/fft.md

Practice problem added for fft. 
Difficulty : Medium

Added extra problem for fft

---

src/graph/kuhn_maximum_bipartite_matching.md
src/index.md

Hi guys,
I recently stumbled upon the problem which used the Hungarian algorithm. I check e-maxx.ru and found that it had a wonderful description for the algorithm which used Kuhn's algorithm as a subroutine. I then went to check Kuhn's algorithm page, and found that it had not yet been translated.
I am creating this PR to translate the page for Kuhn's algorithm, and will translate the page for the Hungarian algorithm once this PR is merged.
Thanks.

Create article for Kuhn's algorithm to find the Maximum Bipartite Matching

---

src/sequences/rmq.md

added rmq problem

---

src/graph/euler_path.md

The current problem name is different than the linked problem.

Correcting the name of the problem

---

src/data_structures/fenwick.md

closing bracket was missing on line 260

fixed typo in fenwick.md

---

src/string/suffix-automaton.md

- Add suffix automata machine (SAM) as an alternate name. I have seen it used in some blog posts and problem comments.
- Fix typos
- Add practice problem

Update suffix automaton

---

src/combinatorics/inclusion-exclusion.md

Fixed typo in "The number of harmonic triplets" topic under combinatorics.

Fixed typo in Inclusion-Exclusion

---

src/graph/edmonds_karp.md

A typo fix in the definition of Integral Flow Theorem.

fix-typo in Integral flow theorem

---

src/algebra/all-submasks.md

Practice problems added to Submask enumeration 

---

src/geometry/halfplane-intersection.md

Minor error in the comments of the half-plane intersection code.

Fix typo in half-plane intersection

---

src/string/prefix-function.md

Try to correct a confusing error in the proof.

Fix a subscript error in the Prefix function page

---

src/graph/01_bfs.md

Fixed typos and grammatical errors to enhance reading experience.

Fixed typos and some grammatical errors

---

src/graph/strongly-connected-components.md

Verified on https://codeforces.com/problemset/submission/949/115129317
Only cosmetic changes were done in majority

Improved the code for generating SCC

---

src/graph/strongly-connected-components.md

Add condensation graph

---

src/algebra/sieve-of-eratosthenes.md

Replaced the vector<char> with vector<bool>, the char vector were initialized with boolean values

Changed the char vectors to boolean vectors

---

src/data_structures/treap.md

As I discussed in the linked issue, I feel that the existing treap code is explained underwhelmingly. Here's a modest attempt at adding more explanation.

Fixes #679: descriptive treap implementation

---

src/contrib.md

FIX: Typo in contrib.md

---

src/graph/lca_binary_lifting.md

Problem link: https://www.codechef.com/problems/LGSEG

Add a practice problem for binary lifting

---

src/string/z-function.md

The original wording is slighty confusing, it took me quite some time to figure the structure of the sentence out.

Clearer wording

---

src/data_structures/segment_tree.md

fixes #736
It Will Now Redirect it to: https://cp-algorithms.com/data_structures/segment_tree.html#implementation

Fixes broken link to impl. of seg. tree

---

src/string/manacher.md

recently I came across manacher's with Prefix-Suffix Palindrome problem and got to know cses problem also. Please add these two to the article as they are good starting problems.

Proposing a problem

---

src/contrib.md

Moving page link in contribution guide.

test.php is now preview.html

---

src/algebra/polynomial.md

Hi! I had some spare time, so I fixed style and some rendering mistakes which occured to lists within article. I also added some useful details to the article.

Improved readability and expansion of polynomial algos article

---

src/algebra/fft.md

Modified the 4 TeX equations under header "Improved implementation: in-place computation"

Updated fft.md by fixing TeX

---

src/data_structures/randomized_heap.md

I think this capture the original intent.
You never know when it comes to notation on probability theory.

Fixed two equations at the end

---

src/graph/01_bfs.md

- Added a minor grammatical correction

fix: sentence tense

---

src/algebra/fft.md

I think this is an interesting problem to test the FFT.

Added Kattis' A+B Problem on FFT

---

src/graph/kuhn_maximum_bipartite_matching.md
src/index.md

Minor edits to correct formatting and typos.

Fix typo in index entry for Kuhn's algorithm, fix formatting

---

src/algebra/binary-exp.md

The Last Power of should have been a^(2^([Log N])) instead of just a^([log N])
Fixing This minor typo

Updating File to fix Issue: #827

---

src/algebra/fibonacci-numbers.md

The old link **https://www.hackerrank.com/contests/codesprint5/challenges/is-fibo/problem** no longer exists.
So I replaced it with a new link **https://www.hackerrank.com/challenges/is-fibo/problem** (same problem).
Please check it.

update "HackerRank - Is Fibo" problem's link

---

src/dynamic_programming/divide-and-conquer-dp.md
src/dynamic_programming/knuth-optimization.md
src/index.md

The commit history is a little messy, and I apologize for that. In short, I added an article on Knuth's optimization in DP, and added a single sentence towards the end of the article on Divide and conquer dp, stating one of the possible conditions under which the optimization can be applied.

Added article on Knuth's optimization; single sentence addition to divide and conquer dp

---

src/algebra/binary-exp.md

Provided coded example of Binary Exp on a permutation

Binary Exp example

---

src/string/suffix-array.md

Fix LCP Out-of-bound error

---

src/graph/edmonds_karp.md

I just did minor improvements in the grammar of the text given on this page: https://cp-algorithms.com/graph/edmonds_karp.html. 
Any other changes required? Please let me know!
🙂

Minor changes in edmonds_karp.md

---

mkdocs.yml
src/contrib.md
src/overrides/main.html
src/overrides/partials/header.html
src/stylesheets/extra.css

@jakobkogler there was a request to bring back next/previous buttons in https://github.com/e-maxx-eng/e-maxx-eng/issues/846. I've added a manual navigation list from the current index page and enabled tabs + sidebar navigation. What do you think of how things look like now?
In my humble opinion, it significantly improves user experience without much of downside. As such, tabs prevent irrelevant articles from being on the navigation bar, hence you won't be suggested string algorithms if you're reading about Eratosthenes sieve.

Enable tabs and sidebar navigation

---

.github/workflows/deploy-prod.yml
.github/workflows/test.yml
mkdocs.yml

With this change, each page will automatically show the date it was updates last time.

Add last revision date

---

.github/workflows/deploy-prod.yml
.github/workflows/test.yml
mkdocs.yml

Reverts e-maxx-eng/e-maxx-eng#868

Revert "Add last revision date"

---

.github/workflows/deploy-prod.yml
.github/workflows/test.yml
hooks.py
mkdocs.yml
src/overrides/main.html
src/overrides/partials/content.html
src/stylesheets/extra.css

This PR is not supposed to be merged yet. Demonstration purposes.

Show the contribution percentile of article authors

---

src/string/string-hashing.md

added [Good Substrings - Codeforces] which is direct use-case of count different substring

added [Good Substrings - Codeforces]

---

.github/workflows/deploy-prod.yml
.github/workflows/test.yml
.gitmodules
src/overrides/partials/content.html

Fix incorrect usernames

---

.github/workflows/deploy-prod.yml
.github/workflows/test.yml
mkdocs.yml
scripts/install-mkdocs.sh
src/contrib.md
src/overrides/partials/content.html

Less duplication, also keep it simpler for new users.

Make install script

---

src/graph/bellman_ford.md

The code to detect negative cycle is correct [here](https://cp-algorithms.com/graph/finding-negative-cycle-in-graph.html#implementation) but incorrect [here](https://cp-algorithms.com/graph/bellman_ford.html#the-case-of-a-negative-cycle).

Incorrect parent initialization in bellman_ford.md

---

src/index.md

return full navigation to the main page

---

src/algebra/factorization.md

Fixed some typos and added brackets to make an equation clearer.

fix typos in factorization.md

---

src/sequences/longest_increasing_subsequence.md

latex block equation rendering fix

---

src/data_structures/segment_tree.md

Data structures are easier to understand when we see what motivates their usecases and construction.

Clarify segment tree wording and add motivation

---

src/string/manacher.md

Add palindrome problems that can be solved by using Manacher's algorithm:
- [SPOJ - Number of Palindromes](https://www.spoj.com/problems/NUMOFPAL/): for those who is new to Manacher's algorithm, and can be solved by using implementation code.
- [Kattis - Palindromes](https://open.kattis.com/problems/palindromes): more difficuilt, use manacher with a little bit data structures.

Add more practice problems for Manacher's algorithm.

---

src/data_structures/sparse-table.md

"respectively" word was misspelled  in the intuition paragraph .

Spelling Correction

---

src/graph/mst_prim.md

Fix a typo in mst_prim.md

---

src/num_methods/ternary_search.md

The removed link is no longer active.

Update practice problems to remove broken links

---

src/data_structures/sparse-table.md

A best practice style PR, shows shiny new C++20 toys.

Add efficient C++20 solution for computing log

---

src/index_body
src/navigation.md
src/num_methods/binary_search.md

I drafted a binary search article some time ago. Making a pull request to better keep track of work on this. It was mentioned earlier in #751.

Binary search article

---

src/data_structures/sparse-table.md

https://codeforces.com/blog/entry/63324?#comment-475826

swap sparse table indexing for better cache performance

---

src/num_methods/binary_search.md

None
There was a typo in binary_search.md docstring that I've noticed and fixed while reading through the site.

fixed a typo in binary_search.md docstring

---

mkdocs.yml
src/javascript/config.js
src/stylesheets/extra.css

Make MathJax selectable

---

src/algebra/binary-exp.md

http://www.usaco.org/current/data/sol_swap_silver_feb20.html - proof is in the java explanation and function at the bottom of the code

Issues within Apply Permutation in Binary Exp

---

src/graph/desopo_pape.md

resolves #980 
I added the reference as a plain markdown link, but feel free to use fancier references if they exist.

D'Esopo-Pape: Add Stack Overflow reference and reword

---

src/graph/mst_prim.md

"for a different side" -> "from a different angle"

Minor language change in Prim's Algo explanation

---

src/algebra/sieve-of-eratosthenes.md

Add simple O(n log n) analysis of sieve

---

src/algebra/binary-exp.md

The old link is down for some reason. So, I added an alternative link for the same problem

fixed link for `Jewel-eating Monsters` problem

---

src/string/manacher.md

Use odd, even instead of 1,2 for marking length

---

src/data_structures/disjoint_set_union.md

Remove disputed linear union-find claims for now

---

src/algebra/factorization.md

Add note on pseudo-polynomial time

---

src/graph/dijkstra_sparse.md

Add details on no-decrease-key Dijkstra's algorithm

---

src/algebra/euclid-algorithm.md

I find the current math formulation to be confusing and hard to read (I especially don't like the use of infinity), so I replaced it with a set-builder notation that translates more easily to the verbal definition.

Clarify gcd math definition

---

src/graph/breadth-first-search.md

At line 184, change link from "https://cses.fi/problemset/result/794325/" to "https://cses.fi/problemset/task/1667/".

Update link for problem CSES - Message Route.

---

src/algebra/extended-euclid-algorithm.md

Cite Bézout's identity

---

src/graph/topological-sort.md

at line 90, change link for problem Ordering Tasks from (https://onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=1246) to (https://onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&page=show_problem&problem=1246)

Update link for Practice Problem - Ordering Tasks

---

src/algebra/factorial-divisors.md

Cite Legendre's Formula (#1019)

---

src/algebra/chinese-remainder-theorem.md

For #1008 since the current page is lacking explanation on actual solutions.
TODO: add C++ sample code

Chinese Remainder Theorem solutions

---

src/geometry/nearest_points.md

Credit Shamos for nearest pair of points algorithm

---

src/data_structures/disjoint_set_union.md

This Pull Request fixes issue #1036.

Fixes typo in DSU article

---

src/algebra/binary-exp.md

Link homogeneous coordinates

---

src/algebra/fibonacci-numbers.md

"LightOJ - Number Sequence" is a problem of Fibonacci Sequence.

add LightOJ - Number Sequence

---

src/algebra/binary-exp.md

Typo: "Module Operator" -> "Modulo Operator"

---

src/string/z-function.md

Both Brave and Edge show spacing issue.

Display issue (spaces vs tabs) with z_function

---

src/string/suffix-automaton.md

Change minlength(v) to minlen(v) for consistency.
Issue #924 improvement.  Will complete after feedback!

Quick edit + Resolved issue #924.

---

src/string/z-function.md

The i + z[i] might be out of range of the string length.  It could cause some undefined behaviour.

fix z_function

---

src/algebra/binary-exp.md

Added a few matrix exponentiation Codeforces problems, roughly sorted all the problems according to their difficulty

Added problems to binary-exp.md

---

src/graph/euler_path.md

This PR adds the missing space :)

Add the missing space

---

mkdocs.yml
scripts/install-mkdocs.sh
src/overrides/partials/header.html

Requested in #1100. Pull request for preview.

Adding RSS plugin

---

README.md

Update a link to use HTTPS for improved security.

Make link safe

---

src/game_theory/sprague-grundy-nim.md

Adds 3 exercises in this topic in ascending order of their difficulty.

Adds practice problems to Sprague-Grundy theorem. Nim

---

src/string/string-hashing.md

Note: I didn't know where to place it in the list, did not see any obvious ordering

Add String Hashing on Kattis as a Practice Problem

---

src/string/suffix-automaton.md

Adds many practice problems directly related to the application section, very useful to test implementations.

Update suffix-automaton.md, adds practice problems

---

src/others/tortoise_and_hare.md

Though there's a lot space between the equations on browser the equations are displayed very nearby. May be it's my personal opinion.

Added a comma for clarity, and rectified minor error in equation

---

src/geometry/point-location.md

Changed an incorrect double negative typo to the intended meaning.

Fix (double-negative) typo in point-location.md

---

src/graph/lca_binary_lifting.md
src/num_methods/binary_search.md

Updated Problem's list of binary_search.md

---

src/num_methods/binary_search.md

Also rearrange sentences. I want to emphasize the idea of a monotonous transition point over the indices L or R themselves. 
#1163

Binary search: brief proof and mention transition point

---

src/combinatorics/inclusion-exclusion.md

Add example problem, general formula, and for that problem, comparison to other approaches. 
Feel free to edit commit messages or anything.

Inclusion-exclusion digit sum problem details

---

src/combinatorics/stars_and_bars.md

Positive integers is a special case of lower bounded integers, but has a nice interpretation.

Stars and bars: add positive integer sum theorem

---

src/sequences/longest_increasing_subsequence.md

Fixed a typo in longest_increasing_subsequence.md

---

src/string/main_lorentz.md

Wrong index.  j>i. Russian site confirms.

Update main_lorentz.md wrong index

---

src/data_structures/segment_tree.md

Attempt to resolve issue #915. Added additional explanation on how to use. Wondered if making arguments than don't change constant makes more sense? Formatted code more similarly to previous versions of segment tree.

Resolving issue #915

---

src/algebra/gray-code.md

Added a good problem from CSES Problemset

Add a problem

---

src/dynamic_programming/knuth-optimization.md

There's no return value. This function should either be void or return the desired value.

No return value in function knuth-optimization.md

---

src/dynamic_programming/divide-and-conquer-dp.md

Allows for copy and paste to be easier.

Incorrect return type + initialized vectors in function

---

src/geometry/minkowski.md

fix typo in minkowski.md issue 

---

src/algebra/euclid-algorithm.md

Codechef Problem is not available anymore, so added new similar problem link

updated the unaccessible problem link

---

README.md
src/dynamic_programming/intro-to-dp.md
src/navigation.md

My attempt to resolve issue #1028. The website needs more about dynamic programming. This is a basic start.

Adding Article: Introduction to Dynamic Programming + Resolving Issue #1028

---

src/combinatorics/stars_and_bars.md

Add new related problems to stars_and_bars.md

---

src/algebra/factorization.md

I have made some editorial changes throughout the article. This should make reading more clear and improve understanding of the material.

Editorial changes to Update factorization.md

---

src/sequences/longest_increasing_subsequence.md

Fix typo in longest_increasing_subsequence.md

---

src/graph/push-relabel-faster.md

We can get final flow value from excess[sink] in the last step.
- P0: `excess[x] == in_flow[x] - out_flo[x]` for all node. // definition
- P1: `out_flow[sink] == 0` at any time. // push will never be run on sink node
- P2: `excess[sink] == in_flow[sink]`
- I have verified with [this problem](https://onlinejudge.u-aizu.ac.jp/problems/GRL_6_A)
``` code
#include <stdio.h>
#include <vector>
const int INF = 100000000;
int V, E;
std::vector<std::vector<int>> capacity;
std::vector<std::vector<int>> flow;
std::vector<int> height;
void input() {
scanf("%d%d", &V, &E);
capacity.resize(V, std::vector<int>(V));
flow.resize(V, std::vector<int>(V));
for (int i = 0; i < E; ++i) {
int u, v, c;
scanf("%d%d%d", &u, &v, &c);
capacity[u][v] = c;
}
}
int source, destination;
std::vector<int> excess;
void …
```

Simplify push-relabel-faster's final step: get final flow value from an existing variable instead of calculation

---

src/graph/min_cost_flow.md

The problem are selected from well-known online judge such as AtCoder and CSES.

Add practice problems for min cost flow

---

src/dynamic_programming/intro-to-dp.md

Changed "programing" to "programming".

Spelling Mistake Fixed

---

src/navigation.md

Changed "Introducton" to "Introduction"

spelling mistake fix

---

src/dynamic_programming/intro-to-dp.md

2 Very Standard Classical Geometry DP problems from Leetcode and 1 great L-R DP like Problem from Codeforces.

Added Practice Problems in intro-to-dp.md

---

src/data_structures/fenwick.md

I tried to improve the grammar and use of notation/definitions in the first few sections.

Refactor portion of Fenwick Tree

---

src/algebra/bit-manipulation.md

Added a new section "Count set bits upto n" under the Useful Tricks section after the Brian Kernighan's algorithm.
The Brian Kernighan's algorithm explains how to count the set bits of an integer n. The new added section explains how to count the set bits of all integers from 1 upto the number n, without giving a TLE during contest submissions.
The Solution was inspired by this [geeksforgeeks problem](https://www.geeksforgeeks.org/problems/count-total-set-bits-1587115620/1)

Added a new section to bit-manipulation.md

---

README.md
src/dynamic_programming/knapsack.md
src/navigation.md

Add knapsack subtopic under Dynamic Programming

Add Knapsack 

---

src/algebra/euclid-algorithm.md

I have included a problem 1916 B (Two divisors) of codeforces which  is rather direct application of this topic.

Included Problem 1916- B Codefroces

---

src/num_methods/ternary_search.md

I just added an easy problem from codeforces  problem [B](https://codeforces.com/contest/1978/problem/B) from [Codeforces Round 953 (Div. 2)](https://codeforces.com/contest/1978)

added new easy problem from codeforces (1978B)

---

src/graph/bridge-searching.md

- Clarified what the `low` array stores (instead of "checking the fact")
- made array text more readable (by using `\mathtt{...}`) 
- added new problem from a recent round: [link](https://codeforces.com/contest/1986/problem/F)

Updates to Bridge Searching in O(N+M)

---

src/algebra/sieve-of-eratosthenes.md

For someone that isn't much familiar with asymptotes it isn't immediate. Is this edit needed?

it doesn't follow immediately

---

.github/workflows/build.yml

Update upload-artifact for workflows

---

src/dynamic_programming/intro-to-dp.md
src/dynamic_programming/knapsack.md

Add practice problems From codeforces and LeetCode

Add practice problems

---

src/graph/01_bfs.md

Fix misspell 01_bfs.md

---

src/game_theory/sprague-grundy-nim.md

I have addded misère game as a slight variation of the nim game in which the last person after which the no. of sticks left are zero or the last person to pick up the remaining stick is zero. Let me know the feedback.

Added misère game as a slight variation of the nim

---

src/graph/edmonds_karp.md

This new statement reflects a more precise description of what the Integral Flow Theorem says, as backed up by the discussion: 
Integral Flow Theorem #1310

Clarifies statement in edmonds_karp.md

---

src/algebra/linear-diophantine-equation.md

I'm not sure if the lemma is extraneous, but it gives an overarching way of understanding linear combinations of integers. The existence of modular inverses mod p can also be proved.

linear-diophantine: add Bézout's lemma and slightly reformat mathjax

---

src/algebra/euclid-algorithm.md

Add 'GCD of multiple numbers' section.

Add 'GCD of multiple numbers' section in euclid-algorithm.md

---

src/sequences/k-th.md

Added [leetcode 215](https://leetcode.com/problems/kth-largest-element-in-an-array/description/) as a practice problem

add problem for k-th statistic

---

src/dynamic_programming/intro-to-dp.md

Some clarification:
* `$O(n)$!` -> `$O(n)$.` not to confused with `$O(n!)$`
* `anyway we like` -> `any way we like`
* `bottom-up`, `DP` for consistency
* some clarifications for non-C++ users
I can also offer Python implementations if that's useful here.

fix: typos and inconsistencies in intro-to-dp

---

src/graph/topological-sort.md

"Otherwise because" might sound confusing to people.
Added commas where needed.

Fix small grammar errors in topological-sort.md

---

src/algebra/phi-function.md

I corrected the typo by removing the extra "all" in the first sentence of [https://cp-algorithms.com/algebra/phi-function.html#etf_1_to_n]. It seems like a small mistake. Thanks for the tutorial, though!

A little spell check that's it

---

mkdocs.yml

Update current year to 2025 in mkdocs.yml, which appears in a footer.

Update current year in mkdocs.yml

---

src/algebra/fft.md

Fix a sentence in fft.md that appears to be incorrectly structured.

Fix sentence structure in fft.md

---

src/graph/hld.md

Added some heavy-light decomposition problems, roughly sorted by difficulty.

Heavy-light decomposition problems

---

src/graph/topological-sort.md

In the implementation example, the if statement within the dfs function is missing a pair of brackets.
Edit: I realize that the brackets are not needed, however in the next function a pair of brackets is used in the same context and the two should be consistent.

Typo fix in topological-sort.md

---

src/combinatorics/burnside.md

Add some Burnside lemma practice problems sorted by difficulty

Burnside lemma practice problems

---

src/string/manacher.md
test/test_manacher_odd.cpp

* fix a small inconsistency in Manacher's algorithm notation for the border of rightmost segment
* write unittest to make sure the implementation remains correct

Manacher's algorithm inconsistency

---

.github/workflows/build.yml
mkdocs.yml
scripts/install-mkdocs.sh

Try mkdocs without navigation tabs

---

src/string/aho_corasick.md

Change text in Aho Corasick

---

src/algebra/fibonacci-numbers.md

In particular, how to derive the identity.

Fibonacci: better motivation for matrix form

---

src/geometry/manhattan-distance.md
src/graph/edmonds_karp.md
src/graph/mst_prim.md
src/graph/second_best_mst.md
src/graph/topological-sort.md

If multiple images where in center tags or center tags had additional text, it wouldn't work.

Update all center tags again

---

src/graph/fixed_length_paths.md

Replaced **if** with **is**.
It is obvious that the constructed adjacency matrix ~~if~~ is the answer to the problem for the case   $k = 1$ . It contains the number of paths of length   $1$  between each pair of vertices.

Typo fix in graph/fixed_length_paths.md

---

README.md
src/geometry/enclosing-circle.md
src/navigation.md

Add minimum enclosing circle article

---

README.md

Reformat README.md for focus on contributing. Reorganize sections to emphasize financial and/or article contribution.

Reformat README.md for focus on contributing

---

src/data_structures/sparse-table.md

Kindly Add this problem to your practice problems list.

Add CSES problem to practice problems list
